#!/bin/bash
set -e
npm i
if [ -d src/index ]; then
  mv src/index .
fi
./gen-index
npm i
./rm-index
mv index src/ 2>/dev/null || echo ''
node ./mk-package.js > dist/package.json
cp README.md dist/
echo "done build-lib."
